// Generated by gencpp from file xela_server/XelaSensorStreamRequest.msg
// DO NOT EDIT!


#ifndef XELA_SERVER_MESSAGE_XELASENSORSTREAMREQUEST_H
#define XELA_SERVER_MESSAGE_XELASENSORSTREAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xela_server
{
template <class ContainerAllocator>
struct XelaSensorStreamRequest_
{
  typedef XelaSensorStreamRequest_<ContainerAllocator> Type;

  XelaSensorStreamRequest_()
    : sensor(0)  {
    }
  XelaSensorStreamRequest_(const ContainerAllocator& _alloc)
    : sensor(0)  {
  (void)_alloc;
    }



   typedef int16_t _sensor_type;
  _sensor_type sensor;





  typedef boost::shared_ptr< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct XelaSensorStreamRequest_

typedef ::xela_server::XelaSensorStreamRequest_<std::allocator<void> > XelaSensorStreamRequest;

typedef boost::shared_ptr< ::xela_server::XelaSensorStreamRequest > XelaSensorStreamRequestPtr;
typedef boost::shared_ptr< ::xela_server::XelaSensorStreamRequest const> XelaSensorStreamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xela_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'xela_server': ['/home/jay/xela/src/xela_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2450d5ef97d4f00e6a15b267632df2ea";
  }

  static const char* value(const ::xela_server::XelaSensorStreamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2450d5ef97d4f00eULL;
  static const uint64_t static_value2 = 0x6a15b267632df2eaULL;
};

template<class ContainerAllocator>
struct DataType< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xela_server/XelaSensorStreamRequest";
  }

  static const char* value(const ::xela_server::XelaSensorStreamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 sensor\n\
";
  }

  static const char* value(const ::xela_server::XelaSensorStreamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct XelaSensorStreamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xela_server::XelaSensorStreamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xela_server::XelaSensorStreamRequest_<ContainerAllocator>& v)
  {
    s << indent << "sensor: ";
    Printer<int16_t>::stream(s, indent + "  ", v.sensor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XELA_SERVER_MESSAGE_XELASENSORSTREAMREQUEST_H
