// Generated by gencpp from file xela_server/XelaSensorXY.msg
// DO NOT EDIT!


#ifndef XELA_SERVER_MESSAGE_XELASENSORXY_H
#define XELA_SERVER_MESSAGE_XELASENSORXY_H

#include <ros/service_traits.h>


#include <xela_server/XelaSensorXYRequest.h>
#include <xela_server/XelaSensorXYResponse.h>


namespace xela_server
{

struct XelaSensorXY
{

typedef XelaSensorXYRequest Request;
typedef XelaSensorXYResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct XelaSensorXY
} // namespace xela_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xela_server::XelaSensorXY > {
  static const char* value()
  {
    return "2f5e77e17dc96027c90e428d83f92b92";
  }

  static const char* value(const ::xela_server::XelaSensorXY&) { return value(); }
};

template<>
struct DataType< ::xela_server::XelaSensorXY > {
  static const char* value()
  {
    return "xela_server/XelaSensorXY";
  }

  static const char* value(const ::xela_server::XelaSensorXY&) { return value(); }
};


// service_traits::MD5Sum< ::xela_server::XelaSensorXYRequest> should match 
// service_traits::MD5Sum< ::xela_server::XelaSensorXY > 
template<>
struct MD5Sum< ::xela_server::XelaSensorXYRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xela_server::XelaSensorXY >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXYRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xela_server::XelaSensorXYRequest> should match 
// service_traits::DataType< ::xela_server::XelaSensorXY > 
template<>
struct DataType< ::xela_server::XelaSensorXYRequest>
{
  static const char* value()
  {
    return DataType< ::xela_server::XelaSensorXY >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXYRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xela_server::XelaSensorXYResponse> should match 
// service_traits::MD5Sum< ::xela_server::XelaSensorXY > 
template<>
struct MD5Sum< ::xela_server::XelaSensorXYResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xela_server::XelaSensorXY >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXYResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xela_server::XelaSensorXYResponse> should match 
// service_traits::DataType< ::xela_server::XelaSensorXY > 
template<>
struct DataType< ::xela_server::XelaSensorXYResponse>
{
  static const char* value()
  {
    return DataType< ::xela_server::XelaSensorXY >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXYResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XELA_SERVER_MESSAGE_XELASENSORXY_H
