// Generated by gencpp from file xela_server/XelaSensorXResponse.msg
// DO NOT EDIT!


#ifndef XELA_SERVER_MESSAGE_XELASENSORXRESPONSE_H
#define XELA_SERVER_MESSAGE_XELASENSORXRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xela_server
{
template <class ContainerAllocator>
struct XelaSensorXResponse_
{
  typedef XelaSensorXResponse_<ContainerAllocator> Type;

  XelaSensorXResponse_()
    : value(0)  {
    }
  XelaSensorXResponse_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::xela_server::XelaSensorXResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xela_server::XelaSensorXResponse_<ContainerAllocator> const> ConstPtr;

}; // struct XelaSensorXResponse_

typedef ::xela_server::XelaSensorXResponse_<std::allocator<void> > XelaSensorXResponse;

typedef boost::shared_ptr< ::xela_server::XelaSensorXResponse > XelaSensorXResponsePtr;
typedef boost::shared_ptr< ::xela_server::XelaSensorXResponse const> XelaSensorXResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xela_server::XelaSensorXResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xela_server::XelaSensorXResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xela_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'xela_server': ['/home/jay/xela/src/xela_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xela_server::XelaSensorXResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xela_server::XelaSensorXResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xela_server::XelaSensorXResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xela_server::XelaSensorXResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xela_server::XelaSensorXResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xela_server::XelaSensorXResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xela_server::XelaSensorXResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9d213e8c146065ec958333c617eb1a6";
  }

  static const char* value(const ::xela_server::XelaSensorXResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9d213e8c146065eULL;
  static const uint64_t static_value2 = 0xc958333c617eb1a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::xela_server::XelaSensorXResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xela_server/XelaSensorXResponse";
  }

  static const char* value(const ::xela_server::XelaSensorXResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xela_server::XelaSensorXResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 value\n\
";
  }

  static const char* value(const ::xela_server::XelaSensorXResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xela_server::XelaSensorXResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct XelaSensorXResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xela_server::XelaSensorXResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xela_server::XelaSensorXResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XELA_SERVER_MESSAGE_XELASENSORXRESPONSE_H
