// Generated by gencpp from file xela_server/XelaSensorStreamResponse.msg
// DO NOT EDIT!


#ifndef XELA_SERVER_MESSAGE_XELASENSORSTREAMRESPONSE_H
#define XELA_SERVER_MESSAGE_XELASENSORSTREAMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <xela_server/SensPoint.h>

namespace xela_server
{
template <class ContainerAllocator>
struct XelaSensorStreamResponse_
{
  typedef XelaSensorStreamResponse_<ContainerAllocator> Type;

  XelaSensorStreamResponse_()
    : xyz()  {
    }
  XelaSensorStreamResponse_(const ContainerAllocator& _alloc)
    : xyz(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::xela_server::SensPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::xela_server::SensPoint_<ContainerAllocator> >::other >  _xyz_type;
  _xyz_type xyz;





  typedef boost::shared_ptr< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> const> ConstPtr;

}; // struct XelaSensorStreamResponse_

typedef ::xela_server::XelaSensorStreamResponse_<std::allocator<void> > XelaSensorStreamResponse;

typedef boost::shared_ptr< ::xela_server::XelaSensorStreamResponse > XelaSensorStreamResponsePtr;
typedef boost::shared_ptr< ::xela_server::XelaSensorStreamResponse const> XelaSensorStreamResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xela_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'xela_server': ['/home/jay/xela/src/xela_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a91068583885a730705f80278ef9b0b0";
  }

  static const char* value(const ::xela_server::XelaSensorStreamResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa91068583885a730ULL;
  static const uint64_t static_value2 = 0x705f80278ef9b0b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xela_server/XelaSensorStreamResponse";
  }

  static const char* value(const ::xela_server::XelaSensorStreamResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SensPoint[] xyz\n\
\n\
================================================================================\n\
MSG: xela_server/SensPoint\n\
uint32 x\n\
uint32 y\n\
uint32 z\n\
";
  }

  static const char* value(const ::xela_server::XelaSensorStreamResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xyz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct XelaSensorStreamResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xela_server::XelaSensorStreamResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xela_server::XelaSensorStreamResponse_<ContainerAllocator>& v)
  {
    s << indent << "xyz[]" << std::endl;
    for (size_t i = 0; i < v.xyz.size(); ++i)
    {
      s << indent << "  xyz[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::xela_server::SensPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.xyz[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XELA_SERVER_MESSAGE_XELASENSORSTREAMRESPONSE_H
