// Generated by gencpp from file xela_server/XelaSensorZ.msg
// DO NOT EDIT!


#ifndef XELA_SERVER_MESSAGE_XELASENSORZ_H
#define XELA_SERVER_MESSAGE_XELASENSORZ_H

#include <ros/service_traits.h>


#include <xela_server/XelaSensorZRequest.h>
#include <xela_server/XelaSensorZResponse.h>


namespace xela_server
{

struct XelaSensorZ
{

typedef XelaSensorZRequest Request;
typedef XelaSensorZResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct XelaSensorZ
} // namespace xela_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xela_server::XelaSensorZ > {
  static const char* value()
  {
    return "fc5714e73aa3fe2b97b854cd8a61a925";
  }

  static const char* value(const ::xela_server::XelaSensorZ&) { return value(); }
};

template<>
struct DataType< ::xela_server::XelaSensorZ > {
  static const char* value()
  {
    return "xela_server/XelaSensorZ";
  }

  static const char* value(const ::xela_server::XelaSensorZ&) { return value(); }
};


// service_traits::MD5Sum< ::xela_server::XelaSensorZRequest> should match 
// service_traits::MD5Sum< ::xela_server::XelaSensorZ > 
template<>
struct MD5Sum< ::xela_server::XelaSensorZRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xela_server::XelaSensorZ >::value();
  }
  static const char* value(const ::xela_server::XelaSensorZRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xela_server::XelaSensorZRequest> should match 
// service_traits::DataType< ::xela_server::XelaSensorZ > 
template<>
struct DataType< ::xela_server::XelaSensorZRequest>
{
  static const char* value()
  {
    return DataType< ::xela_server::XelaSensorZ >::value();
  }
  static const char* value(const ::xela_server::XelaSensorZRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xela_server::XelaSensorZResponse> should match 
// service_traits::MD5Sum< ::xela_server::XelaSensorZ > 
template<>
struct MD5Sum< ::xela_server::XelaSensorZResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xela_server::XelaSensorZ >::value();
  }
  static const char* value(const ::xela_server::XelaSensorZResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xela_server::XelaSensorZResponse> should match 
// service_traits::DataType< ::xela_server::XelaSensorZ > 
template<>
struct DataType< ::xela_server::XelaSensorZResponse>
{
  static const char* value()
  {
    return DataType< ::xela_server::XelaSensorZ >::value();
  }
  static const char* value(const ::xela_server::XelaSensorZResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XELA_SERVER_MESSAGE_XELASENSORZ_H
