// Generated by gencpp from file xela_server/XelaSensorX.msg
// DO NOT EDIT!


#ifndef XELA_SERVER_MESSAGE_XELASENSORX_H
#define XELA_SERVER_MESSAGE_XELASENSORX_H

#include <ros/service_traits.h>


#include <xela_server/XelaSensorXRequest.h>
#include <xela_server/XelaSensorXResponse.h>


namespace xela_server
{

struct XelaSensorX
{

typedef XelaSensorXRequest Request;
typedef XelaSensorXResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct XelaSensorX
} // namespace xela_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xela_server::XelaSensorX > {
  static const char* value()
  {
    return "fc5714e73aa3fe2b97b854cd8a61a925";
  }

  static const char* value(const ::xela_server::XelaSensorX&) { return value(); }
};

template<>
struct DataType< ::xela_server::XelaSensorX > {
  static const char* value()
  {
    return "xela_server/XelaSensorX";
  }

  static const char* value(const ::xela_server::XelaSensorX&) { return value(); }
};


// service_traits::MD5Sum< ::xela_server::XelaSensorXRequest> should match 
// service_traits::MD5Sum< ::xela_server::XelaSensorX > 
template<>
struct MD5Sum< ::xela_server::XelaSensorXRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xela_server::XelaSensorX >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xela_server::XelaSensorXRequest> should match 
// service_traits::DataType< ::xela_server::XelaSensorX > 
template<>
struct DataType< ::xela_server::XelaSensorXRequest>
{
  static const char* value()
  {
    return DataType< ::xela_server::XelaSensorX >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xela_server::XelaSensorXResponse> should match 
// service_traits::MD5Sum< ::xela_server::XelaSensorX > 
template<>
struct MD5Sum< ::xela_server::XelaSensorXResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xela_server::XelaSensorX >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xela_server::XelaSensorXResponse> should match 
// service_traits::DataType< ::xela_server::XelaSensorX > 
template<>
struct DataType< ::xela_server::XelaSensorXResponse>
{
  static const char* value()
  {
    return DataType< ::xela_server::XelaSensorX >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XELA_SERVER_MESSAGE_XELASENSORX_H
