// Generated by gencpp from file xela_server/XelaSensorStream.msg
// DO NOT EDIT!


#ifndef XELA_SERVER_MESSAGE_XELASENSORSTREAM_H
#define XELA_SERVER_MESSAGE_XELASENSORSTREAM_H

#include <ros/service_traits.h>


#include <xela_server/XelaSensorStreamRequest.h>
#include <xela_server/XelaSensorStreamResponse.h>


namespace xela_server
{

struct XelaSensorStream
{

typedef XelaSensorStreamRequest Request;
typedef XelaSensorStreamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct XelaSensorStream
} // namespace xela_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xela_server::XelaSensorStream > {
  static const char* value()
  {
    return "418a22b0f7ffc7c2608fbc4b499d5ce5";
  }

  static const char* value(const ::xela_server::XelaSensorStream&) { return value(); }
};

template<>
struct DataType< ::xela_server::XelaSensorStream > {
  static const char* value()
  {
    return "xela_server/XelaSensorStream";
  }

  static const char* value(const ::xela_server::XelaSensorStream&) { return value(); }
};


// service_traits::MD5Sum< ::xela_server::XelaSensorStreamRequest> should match 
// service_traits::MD5Sum< ::xela_server::XelaSensorStream > 
template<>
struct MD5Sum< ::xela_server::XelaSensorStreamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xela_server::XelaSensorStream >::value();
  }
  static const char* value(const ::xela_server::XelaSensorStreamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xela_server::XelaSensorStreamRequest> should match 
// service_traits::DataType< ::xela_server::XelaSensorStream > 
template<>
struct DataType< ::xela_server::XelaSensorStreamRequest>
{
  static const char* value()
  {
    return DataType< ::xela_server::XelaSensorStream >::value();
  }
  static const char* value(const ::xela_server::XelaSensorStreamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xela_server::XelaSensorStreamResponse> should match 
// service_traits::MD5Sum< ::xela_server::XelaSensorStream > 
template<>
struct MD5Sum< ::xela_server::XelaSensorStreamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xela_server::XelaSensorStream >::value();
  }
  static const char* value(const ::xela_server::XelaSensorStreamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xela_server::XelaSensorStreamResponse> should match 
// service_traits::DataType< ::xela_server::XelaSensorStream > 
template<>
struct DataType< ::xela_server::XelaSensorStreamResponse>
{
  static const char* value()
  {
    return DataType< ::xela_server::XelaSensorStream >::value();
  }
  static const char* value(const ::xela_server::XelaSensorStreamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XELA_SERVER_MESSAGE_XELASENSORSTREAM_H
