// Generated by gencpp from file xela_server/XelaSensorXYZ.msg
// DO NOT EDIT!


#ifndef XELA_SERVER_MESSAGE_XELASENSORXYZ_H
#define XELA_SERVER_MESSAGE_XELASENSORXYZ_H

#include <ros/service_traits.h>


#include <xela_server/XelaSensorXYZRequest.h>
#include <xela_server/XelaSensorXYZResponse.h>


namespace xela_server
{

struct XelaSensorXYZ
{

typedef XelaSensorXYZRequest Request;
typedef XelaSensorXYZResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct XelaSensorXYZ
} // namespace xela_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xela_server::XelaSensorXYZ > {
  static const char* value()
  {
    return "2f5e77e17dc96027c90e428d83f92b92";
  }

  static const char* value(const ::xela_server::XelaSensorXYZ&) { return value(); }
};

template<>
struct DataType< ::xela_server::XelaSensorXYZ > {
  static const char* value()
  {
    return "xela_server/XelaSensorXYZ";
  }

  static const char* value(const ::xela_server::XelaSensorXYZ&) { return value(); }
};


// service_traits::MD5Sum< ::xela_server::XelaSensorXYZRequest> should match 
// service_traits::MD5Sum< ::xela_server::XelaSensorXYZ > 
template<>
struct MD5Sum< ::xela_server::XelaSensorXYZRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xela_server::XelaSensorXYZ >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXYZRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xela_server::XelaSensorXYZRequest> should match 
// service_traits::DataType< ::xela_server::XelaSensorXYZ > 
template<>
struct DataType< ::xela_server::XelaSensorXYZRequest>
{
  static const char* value()
  {
    return DataType< ::xela_server::XelaSensorXYZ >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXYZRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xela_server::XelaSensorXYZResponse> should match 
// service_traits::MD5Sum< ::xela_server::XelaSensorXYZ > 
template<>
struct MD5Sum< ::xela_server::XelaSensorXYZResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xela_server::XelaSensorXYZ >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXYZResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xela_server::XelaSensorXYZResponse> should match 
// service_traits::DataType< ::xela_server::XelaSensorXYZ > 
template<>
struct DataType< ::xela_server::XelaSensorXYZResponse>
{
  static const char* value()
  {
    return DataType< ::xela_server::XelaSensorXYZ >::value();
  }
  static const char* value(const ::xela_server::XelaSensorXYZResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XELA_SERVER_MESSAGE_XELASENSORXYZ_H
