// Generated by gencpp from file xela_server/XelaSensorXYResponse.msg
// DO NOT EDIT!


#ifndef XELA_SERVER_MESSAGE_XELASENSORXYRESPONSE_H
#define XELA_SERVER_MESSAGE_XELASENSORXYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xela_server
{
template <class ContainerAllocator>
struct XelaSensorXYResponse_
{
  typedef XelaSensorXYResponse_<ContainerAllocator> Type;

  XelaSensorXYResponse_()
    : values()  {
    }
  XelaSensorXYResponse_(const ContainerAllocator& _alloc)
    : values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> const> ConstPtr;

}; // struct XelaSensorXYResponse_

typedef ::xela_server::XelaSensorXYResponse_<std::allocator<void> > XelaSensorXYResponse;

typedef boost::shared_ptr< ::xela_server::XelaSensorXYResponse > XelaSensorXYResponsePtr;
typedef boost::shared_ptr< ::xela_server::XelaSensorXYResponse const> XelaSensorXYResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xela_server::XelaSensorXYResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xela_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'xela_server': ['/home/jay/xela/src/xela_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32a5ae1cdb19681174e2cdd288a54bfa";
  }

  static const char* value(const ::xela_server::XelaSensorXYResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32a5ae1cdb196811ULL;
  static const uint64_t static_value2 = 0x74e2cdd288a54bfaULL;
};

template<class ContainerAllocator>
struct DataType< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xela_server/XelaSensorXYResponse";
  }

  static const char* value(const ::xela_server::XelaSensorXYResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] values\n\
";
  }

  static const char* value(const ::xela_server::XelaSensorXYResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct XelaSensorXYResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xela_server::XelaSensorXYResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xela_server::XelaSensorXYResponse_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XELA_SERVER_MESSAGE_XELASENSORXYRESPONSE_H
